import turtle
wn = turtle.Screen()
dice = turtle.Turtle()
dice.color('black')
dice.pensize(5)
for i in range(1,5):
    x = input('What number dice roll do you wish to have? ')
#side 1
    if x ==1:
        dice.pendown()
        dice.forward(40)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(40)
        dice.penup()
        dice.goto(0,40)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.speed(1)
            dice.forward(1)
            dice.right(170)
            dice.penup()
            
        
#side 2
    elif x ==2:
        dice.reset()
        dice.pensize(5)
        dice.pendown()
        dice.forward(40)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(40)
        dice.penup()
        dice.goto(-20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.speed(1)
            dice.forward(1)
            dice.right(170)
            dice.penup()
#side 3
    elif x ==3:
        dice.reset()
        dice.pensize(5)
        dice.pendown()
        dice.forward(40)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(40)
        dice.penup()
        dice.goto(-20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(0,40)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.speed(1)
            dice.forward(1)
            dice.right(170)
            dice.penup()
#side 4
    elif x ==4:
        dice.reset()
        dice.pensize(5)
        dice.pendown()
        dice.forward(40)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(40)
        dice.penup()
        dice.goto(-20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(-20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.speed(1)
            dice.forward(1)
            dice.right(170)
            dice.penup()
    #side 5
    elif x ==5:
        dice.reset()
        dice.pensize(5)
        dice.pendown()
        dice.forward(40)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(40)
        dice.penup()
        dice.goto(-20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(-20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(0,40)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.speed(1)
            dice.forward(1)
            dice.right(170)
            dice.penup()
    #side 6
    elif x ==6:
        dice.reset()
        dice.pensize(5)
        dice.pendown()
        dice.forward(40)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(80)
        dice.left(90)
        dice.forward(40)
        dice.penup()
        dice.goto(-20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(-20,20)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,60)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(-20,40)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.forward(1)
            dice.right(170)
            dice.penup()
        dice.penup()
        dice.goto(20,40)
        dice.pendown()
        for x in range(1,5):
            dice.pensize(10)
            dice.speed(1)
            dice.forward(1)
            dice.right(170)
            dice.penup()
    dice.clear()
